[build]
  command = "npm install --no-audit --no-fund && npm run build"
  functions = "netlify/functions"
  publish = "dist"

[build.environment]
  NODE_VERSION = "18"
  NPM_VERSION = "9"
  PYTHON_VERSION = "3.8"
  # Supabase environment variables should be set in Netlify UI:
  # Site settings → Environment variables → Add new
  # VITE_SUPABASE_URL = your production supabase project URL
  # VITE_SUPABASE_ANON_KEY = your production anon key

[functions]
  # Enable Node.js 18.x runtime
  node_bundler = "esbuild"

[[plugins]]
package = "@netlify/plugin-functions-install-core"
