[build]
  command = "npm install --no-audit --no-fund && npm run build"
  functions = "netlify/functions"
  publish = "dist"

[build.environment]
  NODE_VERSION = "18"
  NPM_VERSION = "9"
  PYTHON_VERSION = "3.8"

[functions]
  # Enable Node.js 18.x runtime
  node_bundler = "esbuild"

[[plugins]]
package = "@netlify/plugin-functions-install-core"
